title: Henri William Paul 
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: Quantitative Economist / Data Scientist / Software Developer 
  <br><br>
  <a href="https://linkedin.com/in/henri-william-paul-54490b265/">LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/Biliprog/">GitHub Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
